# Chapter 3: Progamming in Python

In [2]:
import datascience 
import pandas as pd 
import numpy as np
from datascience import Table
from datascience import *
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('fivethirtyeight')

###### Goal: Replace Minard Dataset example used in [Chapter 3](https://data-8r.gitbooks.io/textbook/chapters/03/4/call-expressions.html "Chapter 3") with CalEnvironscreen dataset. 

### The Data

For this section, we will be using the [CalEnvironScreen 3.0](https://oehha.ca.gov/calenviroscreen/maps-data) dataset from the Ofice of Environmental Health Hazard Assessment. This dataset includes population and pollution data for several counties in California. First, we must import the dataset into our notebook and create a table. We will call this table `ces_data`.

In [67]:
ces_data = Table.read_table('ces_data.csv')
ces_data.take(np.arange(40, 50)).show(5)

If we scroll to the right, we can see a column called `Pesticides`. Notice how a lot of the entries are 0s. When dealing with large datasets, we will often encounter **missing** values. These values are simply empty values that appear when we do not have a value available for a particular record. It is important to clean these meaningless values to carry out analysis of the dataset. Much of data science consists of **cleaning data** which includes **renaming columns**, **reducing the table size to include only the columns of interest**, and **removing missing values.**  

There are various methods of dealing with missing values -- for our purposes, it is safe to simply remove these values from our table.

This has been done for you: simply run the cell below to save a clean and reduced version of the data as `clean_ces_data`. From this point forward, we'll use this cleaned CES data to run our analysis.

To understand our data, it is important to understand what **each row** represents. Notice our first two columns: `California County` & `census_tract`. Each row represents a specific census tract (some specific geographic region) for a given county.  

For instance, our first row represents some small region in the county of Fresno. 

In [22]:
clean_ces_data = Table.read_table('cleaned_data.csv').select('California County', 'census_tract', 'asthma', 'cardiovascular_disease')
clean_ces_data.show(5)

Our dataset contains a lot of entries. Let's narrow down our analysis to the counties of Los Angeles, Alameda, San Francisco, and San Diego

In [53]:
clean_ces_data = clean_ces_data.where('California County', 
                     are.contained_in(['Los Angeles', 'Alameda', 
                                       'San Francisco', 'San Diego']))

### Statistics

In [54]:
clean_ces_data.where('asthma', max(clean_ces_data['asthma']))

California County | census_tract | asthma | cardiovascular_disease
Los Angeles       | 6.0379e+09   | 154.14 | 16.02
Los Angeles       | 6.0379e+09   | 154.14 | 16.02
Los Angeles       | 6.0379e+09   | 154.14 | 16.02
Los Angeles       | 6.0379e+09   | 154.14 | 16.02

In [55]:
clean_ces_data.where('asthma', min(clean_ces_data['asthma']))

California County | census_tract | asthma | cardiovascular_disease
Los Angeles       | 6.0378e+09   | 6.09   | 1.56

In our data, the maximum level of asthma is $ 154.14 $ and the smallest is $ 6.09 $ 

Lets compute the difference between both of these

In [56]:
tract_with_max_asthma = 154.14
tract_with_min_asthma = 6.09

In [57]:
difference = tract_with_max_asthma - tract_with_min_asthma
difference

148.04999999999998

Another important statistic can be the percentage change between the biggest and smallest asthma rates. 

In [58]:
percentage_change = (tract_with_max_asthma - tract_with_min_asthma) / tract_with_max_asthma
percentage_change

0.9604904632152589

Thus, our percentage change between the smallest & largest asthma rates is 98%. This a **big** change, however the minimum and maximum values alone do not tell us the whole story. 

For instance, if we wanted to calculate the percentage change in the first two tracts, we see the first row of our dataset has an asthma rate of $ 21.12 $ and our second row has asthma rate of  $ 30.97 $

We assign names to these numbers so that our code becomes easier to read and our results can be easily interpreted.

In [61]:
clean_ces_data.show(2)

In [62]:
tract_one_asthma = 21.12
tract_two_asthma = 30.97

In [64]:
difference = abs(tract_one_asthma - tract_two_asthma)
difference 

9.849999999999998

Lets calculate the percentage change between these two regions.

In [66]:
abs(tract_one_asthma - tract_two_asthma) / tract_one_asthma

0.46638257575757563

We can see that there is a $ 46 \% $ change in the asthma rates between the first two rows of our dataset.  