# Chapter 3: Progamming in Python

In [1]:
import datascience 
import pandas as pd 
import numpy as np
from datascience import Table
from datascience import *
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.style.use('fivethirtyeight')

###### Goal: Replace Minard Dataset example used in [Chapter 3](https://data-8r.gitbooks.io/textbook/chapters/03/4/call-expressions.html "Chapter 3") with CalEnvironscreen dataset. 

In [2]:
data = Table.read_table('cleaned_data_new.csv')

In [3]:
data.show(3)

### Statistics

In [4]:
max(data['asthma'])

223.3

In [5]:
min(data['asthma'])

3.63

In this table the maximum level of asthma is $ 223.3 $ and the smallest is $ 3.63 $ 

Lets compute the difference between both of these

In [7]:
tract_with_max_asthma = 223.3
tract_with_min_asthma = 3.63

In [8]:
difference = tract_with_max_asthma - tract_with_min_asthma
difference

219.67000000000002

Another important statistic can be the percentage change between the biggest and smallest asthma rates. 

In [10]:
(tract_with_max_asthma - tract_with_min_asthma) / tract_with_max_asthma

0.983743842364532

Since this was not productive in showing the difference since it was so small, we will do the first and second entry of the dataset.  

The first row of our dataset has an asthma rate of $ 131.64 $ and our second row has asthma rate of  $ 60.66 $

We assign names to these numbers so that our code becomes easier to read and our results can be easily interpreted.

In [11]:
tract_one_asthma = 131.64
tract_two_asthma = 60.66

In [12]:
difference = tract_one_asthma - tract_two_asthma
difference 

70.97999999999999

Lets calculate the percentage change between these two regions.

In [13]:
(tract_one_asthma - tract_two_asthma) / tract_one_asthma

0.5391978122151322

We can see that there is a 53% change in the asthma rates between the first two rows of our dataset.  


Things to do: 

 -- Bring context into the tracts -- which tracts belong to which areas.  
 -- Is asthma rate higher in predomenintly poor neighborhoods?